import { APISchema, DetectedPatterns, Endpoint, TemplateContext, EndpointContext, ParamContext } from '../schema/api-schema.js';

export function buildTemplateContext(
  schema: APISchema,
  patterns: DetectedPatterns,
  absolutePath?: string
): TemplateContext {
  const usedNames = new Map<string, number>();

  return {
    name: schema.name,
    baseUrl: schema.baseUrl,
    auth: schema.auth,
    endpoints: schema.endpoints.map(ep => buildEndpoint(ep, usedNames)),
    patterns,
    absolutePath,
    envPrefix: toEnvPrefix(schema.name),
  };
}

function buildEndpoint(ep: Endpoint, usedNames: Map<string, number>): EndpointContext {
  const toolName = generateToolName(ep, usedNames);

  const pathParams: ParamContext[] = ep.parameters
    .filter(p => p.in === 'path')
    .map(toParamContext);

  const queryParams: ParamContext[] = ep.parameters
    .filter(p => p.in === 'query')
    .map(toParamContext);

  const bodyParams: ParamContext[] = [];
  if (ep.requestBody?.schema?.properties) {
    for (const [name, schema] of Object.entries(ep.requestBody.schema.properties)) {
      bodyParams.push({
        name,
        type: schema.type || 'string',
        required: ep.requestBody.schema.required?.includes(name) || false,
        description: '',
      });
    }
  }

  const allParams = [...pathParams, ...queryParams, ...bodyParams];
  const requiredParams = allParams.filter(p => p.required).map(p => p.name);
  const hasBody = bodyParams.length > 0 || ['POST', 'PUT', 'PATCH'].includes(ep.method);

  return {
    toolName,
    description: ep.description,
    method: ep.method,
    pathTemplate: ep.path,
    pathParams,
    queryParams,
    bodyParams,
    hasBody,
    allParams,
    requiredParams,
  };
}

function toParamContext(p: { name: string; schema: { type: string }; required: boolean; description?: string }): ParamContext {
  return {
    name: p.name,
    type: p.schema.type || 'string',
    required: p.required,
    description: p.description || '',
  };
}

function generateToolName(ep: Endpoint, usedNames: Map<string, number>): string {
  let name = ep.id;

  const isAutoGenerated = /Using(GET|POST|PUT|PATCH|DELETE)$/i.test(name)
    || /^(get|post|put|patch|delete|list|add|update|remove|create|link|search)_\d+$/i.test(name)
    || /^(get|post|put|patch|delete)_[/_]/.test(name);

  if (isAutoGenerated || !name) {
    name = deriveFromPath(ep.method, ep.path);
  }

  const count = usedNames.get(name) || 0;
  usedNames.set(name, count + 1);
  if (count > 0) {
    name = `${name}_${count + 1}`;
  }

  return name;
}

function deriveFromPath(method: string, path: string): string {
  const segments = path
    .split('/')
    .filter(s => s && !s.startsWith('{'));

  const resource = segments.length > 0
    ? segments[segments.length - 1]
    : 'resource';

  const singular = resource.endsWith('s') ? resource.slice(0, -1) : resource;
  const hasPathParam = path.includes('{');

  const methodMap: Record<string, string> = {
    GET: hasPathParam ? `get${capitalize(singular)}` : `list${capitalize(resource)}`,
    POST: `create${capitalize(singular)}`,
    PUT: `update${capitalize(singular)}`,
    PATCH: `update${capitalize(singular)}`,
    DELETE: `delete${capitalize(singular)}`,
  };

  return methodMap[method] || `${method.toLowerCase()}${capitalize(resource)}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toEnvPrefix(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .toUpperCase();
}
