import { APISchema, DetectedPatterns, Endpoint, TemplateContext, EndpointContext, ParamContext } from '../schema/api-schema.js';

export function buildTemplateContext(
  schema: APISchema,
  patterns: DetectedPatterns,
  absolutePath?: string
): TemplateContext {
  const usedNames = new Map<string, number>();

  return {
    name: schema.name,
    packageName: toPackageName(schema.name),
    displayDescription: toDisplayDescription(schema.name),
    baseUrl: schema.baseUrl,
    auth: schema.auth,
    endpoints: schema.endpoints.map(ep => buildEndpoint(ep, usedNames)),
    patterns,
    absolutePath,
    envPrefix: toEnvPrefix(schema.name),
  };
}

function buildEndpoint(ep: Endpoint, usedNames: Map<string, number>): EndpointContext {
  const toolName = generateToolName(ep, usedNames);

  const pathParams: ParamContext[] = ep.parameters
    .filter(p => p.in === 'path')
    .map(toParamContext);

  const queryParams: ParamContext[] = ep.parameters
    .filter(p => p.in === 'query')
    .map(toParamContext);

  const bodyParams: ParamContext[] = [];
  if (ep.requestBody?.schema?.properties) {
    for (const [name, schema] of Object.entries(ep.requestBody.schema.properties)) {
      bodyParams.push({
        name,
        type: schema.type || 'string',
        required: ep.requestBody.schema.required?.includes(name) || false,
        description: '',
      });
    }
  }

  // Deduplicate params by name: body params override query params of the same name
  const paramMap = new Map<string, ParamContext>();
  for (const p of [...pathParams, ...queryParams, ...bodyParams]) {
    paramMap.set(p.name, p);
  }
  const allParams = Array.from(paramMap.values());
  const requiredParams = allParams.filter(p => p.required).map(p => p.name);
  const hasBody = bodyParams.length > 0 || ['POST', 'PUT', 'PATCH'].includes(ep.method);

  return {
    toolName,
    description: ep.description,
    method: ep.method,
    pathTemplate: ep.path,
    pathParams,
    queryParams,
    bodyParams,
    hasBody,
    allParams,
    requiredParams,
  };
}

function toParamContext(p: { name: string; schema: { type: string }; required: boolean; description?: string }): ParamContext {
  return {
    name: p.name,
    type: p.schema.type || 'string',
    required: p.required,
    description: p.description || '',
  };
}

function generateToolName(ep: Endpoint, usedNames: Map<string, number>): string {
  let name = ep.id;

  const isAutoGenerated = /Using(GET|POST|PUT|PATCH|DELETE)/i.test(name)
    || /^(get|post|put|patch|delete|list|add|update|remove|create|link|search)_\d+$/i.test(name)
    || /^(get|post|put|patch|delete)_[/_]/.test(name)
    || /Using(GET|POST|PUT|PATCH|DELETE)_\d+$/i.test(name);

  if (isAutoGenerated || !name) {
    name = deriveFromPath(ep.method, ep.path);
  }

  // Sanitize: convert hyphens/dots/spaces to camelCase so the name is a valid TS identifier
  name = toCamelCase(name);

  const count = usedNames.get(name) || 0;
  usedNames.set(name, count + 1);
  if (count > 0) {
    name = `${name}_${count + 1}`;
  }

  return name;
}

/**
 * Convert a string with hyphens, dots, or spaces into camelCase.
 * e.g. "get-an-album" -> "getAnAlbum", "some.thing" -> "someThing"
 */
function toCamelCase(str: string): string {
  // Replace any non-alphanumeric/underscore chars with a separator, then camelCase
  return str
    .replace(/[^a-zA-Z0-9_]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/[^a-zA-Z0-9_]/g, '');
}

function deriveFromPath(method: string, path: string): string {
  const segments = path
    .split('/')
    .filter(s => s && !s.startsWith('{'));

  const resource = segments.length > 0
    ? segments[segments.length - 1]
    : 'resource';

  const singular = resource.endsWith('s') ? resource.slice(0, -1) : resource;
  const hasPathParam = path.includes('{');

  const methodMap: Record<string, string> = {
    GET: hasPathParam ? `get${capitalize(singular)}` : `list${capitalize(resource)}`,
    POST: `create${capitalize(singular)}`,
    PUT: `update${capitalize(singular)}`,
    PATCH: `update${capitalize(singular)}`,
    DELETE: `delete${capitalize(singular)}`,
  };

  return methodMap[method] || `${method.toLowerCase()}${capitalize(resource)}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toPackageName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    + '-mcp';
}

function toDisplayDescription(name: string): string {
  // Avoid "Weather API API" — only append "API" if name doesn't already contain it
  if (/\bapi\b/i.test(name)) {
    return `MCP server for ${name}`;
  }
  return `MCP server for the ${name} API`;
}

function toEnvPrefix(name: string): string {
  // Use only the first few meaningful words to avoid absurdly long env var names
  const prefix = name
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .toUpperCase();
  // Cap at first 3 segments (e.g. "SPOTIFY_WEB_API" not "SPOTIFY_WEB_API_WITH_FIXES_AND_...")
  const segments = prefix.split('_');
  if (segments.length > 3) {
    return segments.slice(0, 3).join('_');
  }
  return prefix;
}
